In [1]:
import os
from PIL import Image
import numpy as np

dir_path = "/home/ubuntu/code/Marigold/output/data/input-depth-2/depth_bw"

for filename in os.listdir(dir_path):
    if filename.endswith((".png", ".jpg")):
        filepath = os.path.join(dir_path, filename)
        img = Image.open(filepath)
        img_array = np.array(img)
        img_array = img_array.astype(np.float32)  
        img_array /= 65535.0
        img_array *= 255
        img_array = img_array.astype(np.uint8)
        print(f"Image: {filename}")
        print(f"Shape: {img_array.shape}")
        print(f"Representation: {img_array}")
    break

Image: winter_new_york_09046_pred.png
Shape: (480, 640)
Representation: [[50 51 51 ... 40 40 40]
 [51 51 52 ... 39 39 39]
 [51 52 52 ... 39 39 39]
 ...
 [45 45 44 ... 31 32 32]
 [45 44 44 ... 31 31 32]
 [46 44 44 ... 30 30 29]]


In [26]:
import os
from PIL import Image
import numpy as np

# specify the directory
dir_path = "/home/ubuntu/code/data/input"

# list all files in directory
for filename in os.listdir(dir_path):
    print(filename)
    if filename.endswith((".png", ".jpg")):
        # print("j")
        # construct full file path
        filepath = os.path.join(dir_path, filename)
        # open image
        img = Image.open(filepath)
        # convert image to numpy array
        img_array = np.array(img)
        # print shape and representation
        print(f"Image: {filename}")
        print(f"Shape: {img_array.shape}")
        print(f"Representation: {img_array}")
    break

winter__street_01899.jpg
Image: winter__street_01899.jpg
Shape: (480, 640, 3)
Representation: [[[ 52  61  30]
  [ 74  82  61]
  [ 75  79  80]
  ...
  [102 133  99]
  [100 130 104]
  [106 136 112]]

 [[ 62  71  44]
  [ 71  78  62]
  [ 67  71  74]
  ...
  [ 73 103  69]
  [ 81 109  84]
  [120 148 125]]

 [[ 85  93  72]
  [ 83  89  77]
  [ 63  67  70]
  ...
  [ 66  93  60]
  [ 58  84  57]
  [ 96 121  99]]

 ...

 [[110 139  75]
  [113 141  82]
  [175 203 152]
  ...
  [ 73 123  64]
  [ 39  92  36]
  [126 181 126]]

 [[110 134  82]
  [108 134  86]
  [124 151 110]
  ...
  [ 64 121  66]
  [ 48 108  56]
  [135 197 146]]

 [[ 83 106  60]
  [141 164 122]
  [ 42  66  32]
  ...
  [ 41 103  52]
  [ 48 114  66]
  [170 238 191]]]


In [33]:
import os
import cv2
import shutil
import numpy as np

# Define input and output directories
depth_dir = "/home/ubuntu/code/Marigold/output/data/input-depth-2/depth_bw"
color_dir = "/home/ubuntu/code/data/input"
gt_dir = "/home/ubuntu/code/data/gt"
output_dir = "/home/ubuntu/code/TransWeather/data/train"

# Create output directories if they don't exist
train_input_dir = os.path.join(output_dir, "input")
train_gt_dir = os.path.join(output_dir, "gt")
os.makedirs(train_input_dir, exist_ok=True)
os.makedirs(train_gt_dir, exist_ok=True)

# Iterate through files in depth directory
for depth_file in os.listdir(depth_dir):
    if depth_file.endswith((".png", ".jpg")):
        # Extract number from depth file name
        num = depth_file.split("_")[0]

        # Read depth image
        depth_img = cv2.imread(os.path.join(depth_dir, depth_file), cv2.IMREAD_UNCHANGED)

        # Read corresponding color image
        color_file = f"{num}_rain.png"
        color_img = cv2.imread(os.path.join(color_dir, color_file))

        # Check if color image exists
        if color_img is not None:
            # Resize depth image to match color image size
            depth_img_resized = cv2.resize(depth_img, (color_img.shape[1], color_img.shape[0]))

            # Map depth values to 0-255 range
            depth_img_mapped = (depth_img_resized / 65535.0) * 255.0
            depth_img_mapped = depth_img_mapped.astype(np.uint8)

            # Add depth as fourth channel to color image
            color_img_with_depth = np.dstack((color_img, depth_img_mapped))

            # Save the resulting image in the input directory
            output_file_input = os.path.join(train_input_dir, f"{num}_rain.png")
            cv2.imwrite(output_file_input, color_img_with_depth)

            # Copy corresponding gt image to gt directory
            shutil.copy(os.path.join(gt_dir, color_file), train_gt_dir)

            print(f"Processed: {depth_file}")

print("All files processed successfully.")


Processed: 272_rain_pred.png
Processed: 159_rain_pred.png
Processed: 27_rain_pred.png
Processed: 30_rain_pred.png
Processed: 385_rain_pred.png
Processed: 130_rain_pred.png
Processed: 336_rain_pred.png
Processed: 195_rain_pred.png
Processed: 231_rain_pred.png
Processed: 316_rain_pred.png
Processed: 10_rain_pred.png
Processed: 481_rain_pred.png
Processed: 125_rain_pred.png
Processed: 228_rain_pred.png
Processed: 412_rain_pred.png
Processed: 198_rain_pred.png
Processed: 254_rain_pred.png
Processed: 294_rain_pred.png
Processed: 258_rain_pred.png
Processed: 389_rain_pred.png
Processed: 215_rain_pred.png
Processed: 490_rain_pred.png
Processed: 425_rain_pred.png
Processed: 458_rain_pred.png
Processed: 443_rain_pred.png
Processed: 427_rain_pred.png
Processed: 243_rain_pred.png
Processed: 463_rain_pred.png
Processed: 22_rain_pred.png
Processed: 221_rain_pred.png
Processed: 188_rain_pred.png
Processed: 233_rain_pred.png
Processed: 449_rain_pred.png
Processed: 469_rain_pred.png
Processed: 405_rai

In [5]:
import os

folder_path = '/home/ubuntu/code/TransWeather/data/test/input'

output_file_path = '/home/ubuntu/code/TransWeather/data/test/depth_input_test.txt'

file_names = os.listdir(folder_path)

image_extensions = ['.jpg', '.jpeg', '.png', '.bmp']
image_file_names = [file for file in file_names if any(file.endswith(ext) for ext in image_extensions)]

with open(output_file_path, 'w') as file:
    for image_name in image_file_names:
        file.write(f"./input/{image_name}\n")

print(f"File names have been saved to {output_file_path}")

File names have been saved to /home/ubuntu/code/TransWeather/data/train/depth_input_test.txt


In [2]:
import os
import cv2
import shutil
import numpy as np

# Define input and output directories
depth_dir = "/home/ubuntu/code/Marigold/output/data/input-depth-2/depth_bw"
color_dir = "/home/ubuntu/code/data/input"
gt_dir = "/home/ubuntu/code/data/gt"
output_dir = "/home/ubuntu/code/TransWeather/data/train"

# Create output directories if they don't exist
train_input_dir = os.path.join(output_dir, "input")
train_gt_dir = os.path.join(output_dir, "gt")
os.makedirs(train_input_dir, exist_ok=True)
os.makedirs(train_gt_dir, exist_ok=True)

def find_file_by_basename(directory, base_name):
    """Find a file in the specified directory that matches the base_name, ignoring file extension."""
    for file in os.listdir(directory):
        if os.path.splitext(file)[0] == base_name:
            return file
    return None  # Return None if no file matches

# Iterate through files in depth directory
for depth_file in os.listdir(depth_dir):
    if depth_file.endswith(".png"):
        # Extract base filename without the extension and remove '_pred' suffix
        base_name = os.path.splitext(depth_file)[0].replace('_pred', '')

        # Find corresponding color image
        color_file = find_file_by_basename(color_dir, base_name)
        if color_file:
            # Read depth image
            depth_img = cv2.imread(os.path.join(depth_dir, depth_file), cv2.IMREAD_UNCHANGED)

            # Read corresponding color image
            color_img = cv2.imread(os.path.join(color_dir, color_file))

            # Resize depth image to match color image size
            depth_img_resized = cv2.resize(depth_img, (color_img.shape[1], color_img.shape[0]))

            # Map depth values to 0-255 range
            depth_img_mapped = (depth_img_resized / 65535.0) * 255.0
            depth_img_mapped = depth_img_mapped.astype(np.uint8)

            # Add depth as fourth channel to color image
            color_img_with_depth = np.dstack((color_img, depth_img_mapped))

            # Save the resulting image in the input directory with .png extension
            output_file_input = os.path.join(train_input_dir, f"{base_name}.png")
            cv2.imwrite(output_file_input, color_img_with_depth)

            # Find and copy corresponding gt image to gt directory, ensuring output is .png
            gt_file = find_file_by_basename(gt_dir, base_name)
            if gt_file:
                shutil.copy(os.path.join(gt_dir, gt_file), os.path.join(train_gt_dir, f"{base_name}.png"))

            # print(f"Processed: {depth_file}")

print("All files processed successfully.")


All files processed successfully.


In [3]:
import os
import shutil
import random

# Define the directories for training and testing data
train_gt_dir = "/home/ubuntu/code/TransWeather/data/train/gt"
train_input_dir = "/home/ubuntu/code/TransWeather/data/train/input"
test_gt_dir = "/home/ubuntu/code/TransWeather/data/test/gt"
test_input_dir = "/home/ubuntu/code/TransWeather/data/test/input"

# Create test directories if they don't exist
os.makedirs(test_gt_dir, exist_ok=True)
os.makedirs(test_input_dir, exist_ok=True)

# Get list of files in the ground truth train directory
gt_files = os.listdir(train_gt_dir)

# Calculate 10% of the files
num_files_to_move = max(1, len(gt_files) // 10)

# Randomly select files to move
files_to_move = random.sample(gt_files, num_files_to_move)

# Move selected files from train to test directories
for file in files_to_move:
    # Move ground truth file
    shutil.move(os.path.join(train_gt_dir, file), os.path.join(test_gt_dir, file))
    
    # Move corresponding input file
    input_file = file  # Assuming the input file has the same name
    shutil.move(os.path.join(train_input_dir, input_file), os.path.join(test_input_dir, input_file))

print(f"Moved {num_files_to_move} files to test directories successfully.")


Moved 1806 files to test directories successfully.


In [ ]:
import os
import random
from PIL import Image

# specify your path
path = "/home/ec2-user/TransWeather/data"

# get list of all files
files = os.listdir(path)
# filter out all non-image files
images = [file for file in files if file.endswith(('jpg', 'png', 'jpeg'))]

# pick a random image
random_image_name = random.choice(images)
random_image_path = os.path.join(path, random_image_name)

# open the image
img = Image.open(random_image_path)

# check if it has 4 channels
if len(img.split()) == 4:
    # loop through all images
    for image_name in images:
        image_path = os.path.join(path, image_name)
        img = Image.open(image_path)
        # if image has 4 channels
        if len(img.split()) == 4:
            # delete the fourth channel
            r, g, b, a = img.split()
            img = Image.merge("RGB", (r, g, b))
            # save back to the original image
            img.save(image_path)

: 